SymbolCsharpDualSDK: CatSdk.NetworkTimestampDatetimeConverter Class Reference
CatSdk.NetworkTimestampDatetimeConverter Class Reference
Public Member Functions
NetworkTimestampDatetimeConverter (DateTime epoch, string timeUnits)
DateTime ToDatetime (ulong rawTimestamp)
ulong ToDifference (DateTime referenceDatetime)
Public Attributes
DateTime Epoch
int TimeUnits
Static Private Member Functions
static int GetTimeUnits (string timeUnits)
Detailed Description
Provides utilities for converting between network timestamps and datetimes.
Constructor & Destructor Documentation
NetworkTimestampDatetimeConverter()
CatSdk.NetworkTimestampDatetimeConverter.NetworkTimestampDatetimeConverter (DateTime epoch, string timeUnits) inline
Creates a converter given an epoch and base time units.
Parameters
{DateTime} epoch Date at which network started.
{string} timeUnits Time unit the network uses for progressing.
References CatSdk.NetworkTimestampDatetimeConverter.Epoch, CatSdk.NetworkTimestampDatetimeConverter.GetTimeUnits(), and CatSdk.NetworkTimestampDatetimeConverter.TimeUnits.
Member Function Documentation
GetTimeUnits()
static int CatSdk.NetworkTimestampDatetimeConverter.GetTimeUnits (string timeUnits) inline static private
Referenced by CatSdk.NetworkTimestampDatetimeConverter.NetworkTimestampDatetimeConverter().
ToDatetime()
DateTime CatSdk.NetworkTimestampDatetimeConverter.ToDatetime (ulong rawTimestamp) inline
Converts a network timestamp to a datetime.
Parameters
{ulong} rawTimestamp Raw network timestamp.
Returns
{DateTime} Date representation of the network timestamp.
References CatSdk.NetworkTimestampDatetimeConverter.Epoch, and CatSdk.NetworkTimestampDatetimeConverter.TimeUnits.
Referenced by CatSdk.BaseNetwork< T >.ToDatetime().
ToDifference()
ulong CatSdk.NetworkTimestampDatetimeConverter.ToDifference (DateTime referenceDatetime) inline
Subtracts the network epoch from the reference date.
Parameters
{Date} referenceDatetime Reference date.
Returns
{number} Number of network time units between the reference date and the network epoch.
References CatSdk.NetworkTimestampDatetimeConverter.Epoch, and CatSdk.NetworkTimestampDatetimeConverter.TimeUnits.
Referenced by CatSdk.BaseNetwork< T >.FromDatetime< E >().
Member Data Documentation
Epoch
DateTime CatSdk.NetworkTimestampDatetimeConverter.Epoch
Referenced by CatSdk.NetworkTimestampDatetimeConverter.NetworkTimestampDatetimeConverter(), CatSdk.NetworkTimestampDatetimeConverter.ToDatetime(), and CatSdk.NetworkTimestampDatetimeConverter.ToDifference().
TimeUnits
int CatSdk.NetworkTimestampDatetimeConverter.TimeUnits
Referenced by CatSdk.NetworkTimestampDatetimeConverter.NetworkTimestampDatetimeConverter(), CatSdk.NetworkTimestampDatetimeConverter.ToDatetime(), and CatSdk.NetworkTimestampDatetimeConverter.ToDifference().
The documentation for this class was generated from the following file:
NetworkTimestamp.cs