SymbolCsharpDualSDK: CatSdk.NetworkTimestamp Class Reference
CatSdk.NetworkTimestamp Class Reference
Public Member Functions
NetworkTimestamp (ulong timestamp)
bool IsEpochal ()
virtual NetworkTimestamp AddSeconds (ulong count)
NetworkTimestamp AddMinutes (ulong count)
NetworkTimestamp AddHours (ulong count)
override string ToString ()
Public Attributes
readonly ulong Timestamp
Detailed Description
Represents a network timestamp.
Constructor & Destructor Documentation
NetworkTimestamp()
CatSdk.NetworkTimestamp.NetworkTimestamp (ulong timestamp) inline
Creates a timestamp.
Parameters
{ulong} timestamp Raw network timestamp.
References CatSdk.NetworkTimestamp.Timestamp.
Member Function Documentation
AddHours()
NetworkTimestamp CatSdk.NetworkTimestamp.AddHours (ulong count) inline
Adds a specified number of hours to this timestamp.
Parameters
{ulong} count Number of hours to add.
Returns
{NetworkTimestamp} New timestamp that is the specified number of hours past this timestamp.
References CatSdk.NetworkTimestamp.AddMinutes().
AddMinutes()
NetworkTimestamp CatSdk.NetworkTimestamp.AddMinutes (ulong count) inline
Adds a specified number of minutes to this timestamp.
Parameters
{ulong} count Number of minutes to add.
Returns
{NetworkTimestamp} New timestamp that is the specified number of minutes past this timestamp.
References CatSdk.NetworkTimestamp.AddSeconds().
Referenced by CatSdk.NetworkTimestamp.AddHours().
AddSeconds()
virtual NetworkTimestamp CatSdk.NetworkTimestamp.AddSeconds (ulong count) inline virtual
Adds a specified number of seconds to this timestamp. @abstract
Parameters
{ulong} count Number of seconds to add.
Returns
{NetworkTimestamp} New timestamp that is the specified number of seconds past this timestamp.
Reimplemented in CatSdk.Nem.NetworkTimestamp, and CatSdk.Symbol.NetworkTimestamp.
Referenced by CatSdk.NetworkTimestamp.AddMinutes().
IsEpochal()
bool CatSdk.NetworkTimestamp.IsEpochal () inline
Determines if this is the epochal timestamp.
References CatSdk.NetworkTimestamp.Timestamp.
ToString()
override string CatSdk.NetworkTimestamp.ToString () inline
Returns string representation of this object.
Returns
{string} String representation of this object
References CatSdk.NetworkTimestamp.Timestamp.
Member Data Documentation
Timestamp
readonly ulong CatSdk.NetworkTimestamp.Timestamp
Referenced by CatSdk.NetworkTimestamp.IsEpochal(), CatSdk.NetworkTimestamp.NetworkTimestamp(), CatSdk.BaseNetwork< T >.ToDatetime(), and CatSdk.NetworkTimestamp.ToString().
The documentation for this class was generated from the following file:
NetworkTimestamp.cs