SymbolCsharpDualSDK: CatSdk.BaseNetwork< T > Class Template Reference
CatSdk.BaseNetwork< T > Class Template Reference
Public Member Functions
T PublicKeyToAddress (string publicKey)
T PublicKeyToAddress (byte[] publicKey)
DateTime ToDatetime (NetworkTimestamp referenceNetworkTimestamp)
E FromDatetime< E > (DateTime referenceDatetime)
override string ToString ()
Public Attributes
readonly string Name
readonly byte Identifier
readonly NetworkTimestampDatetimeConverter DatetimeConverter
readonly KeccakDigest AddressHasher
readonly Func< byte[], byte[], T > CreateAddress
Type AddressClass
readonly Type NetworkTimestampClass
Protected Member Functions
BaseNetwork (string name, byte identifier, NetworkTimestampDatetimeConverter datetimeConverter, KeccakDigest addressHasher, Func< byte[], byte[], T > createAddress, Type addressClass, Type networkTimestampClass)
Detailed Description
Represents a network.
Constructor & Destructor Documentation
BaseNetwork()
CatSdk.BaseNetwork< T >.BaseNetwork (string name, byte identifier, NetworkTimestampDatetimeConverter datetimeConverter, KeccakDigest addressHasher, Func< byte[], byte[], T > createAddress, Type addressClass, Type networkTimestampClass) inline protected
Creates a new network with the specified name and identifier byte.
Parameters
{string} name Network name.
{byte} identifier Network identifier byte.
{NetworkTimestampDatetimeConverter} datetimeConverter Network timestamp datetime converter associated with this network.
{KeccakDigest} addressHasher Gets the primary hasher to use in the public key to address conversion.
{Func} createAddress Creates an encoded address from an address without checksum and checksum bytes.
{Type} AddressClass Address class associated with this network.
{Type} NetworkTimestampClass Network timestamp class associated with this network.
References CatSdk.BaseNetwork< T >.AddressClass, CatSdk.BaseNetwork< T >.AddressHasher, CatSdk.BaseNetwork< T >.CreateAddress, CatSdk.BaseNetwork< T >.DatetimeConverter, CatSdk.BaseNetwork< T >.Identifier, CatSdk.BaseNetwork< T >.Name, and CatSdk.BaseNetwork< T >.NetworkTimestampClass.
Member Function Documentation
FromDatetime< E >()
E CatSdk.BaseNetwork< T >.FromDatetime< E > (DateTime referenceDatetime) inline
Converts a datetime to a network timestamp.
Parameters
{DateTime} referenceDatetime Reference datetime to convert.
Returns
{NetworkTimestamp} Network timestamp representation of the reference datetime.
Type Constraints
E : NetworkTimestamp
References CatSdk.BaseNetwork< T >.DatetimeConverter, CatSdk.BaseNetwork< T >.NetworkTimestampClass, and CatSdk.NetworkTimestampDatetimeConverter.ToDifference().
PublicKeyToAddress() [1/2]
T CatSdk.BaseNetwork< T >.PublicKeyToAddress (byte[] publicKey) inline
Converts a public key to an address.
Parameters
{PublicKey} publicKey Public key to convert.
Returns
{Address} Address corresponding to the public key input.
References CatSdk.BaseNetwork< T >.AddressHasher, CatSdk.BaseNetwork< T >.CreateAddress, and CatSdk.BaseNetwork< T >.Identifier.
PublicKeyToAddress() [2/2]
T CatSdk.BaseNetwork< T >.PublicKeyToAddress (string publicKey) inline
Converts a public key to an address.
Parameters
{PublicKey} publicKey Public key to convert.
Returns
{Address} Address corresponding to the public key input.
References CatSdk.Utils.Converter.HexToBytes(), and CatSdk.BaseNetwork< T >.PublicKeyToAddress().
Referenced by CatSdk.Symbol.Factory.TransactionsFactory.Create(), CatSdk.Symbol.Factory.TransactionsFactory.CreateEmbedded(), and CatSdk.BaseNetwork< T >.PublicKeyToAddress().
ToDatetime()
DateTime CatSdk.BaseNetwork< T >.ToDatetime (NetworkTimestamp referenceNetworkTimestamp) inline
Converts a network timestamp to a datetime.
Parameters
{NetworkTimestamp} referenceNetworkTimestamp Reference network timestamp to convert.
Returns
{DateTime} Datetime representation of the reference network timestamp.
References CatSdk.BaseNetwork< T >.DatetimeConverter, CatSdk.NetworkTimestamp.Timestamp, and CatSdk.NetworkTimestampDatetimeConverter.ToDatetime().
ToString()
override string CatSdk.BaseNetwork< T >.ToString () inline
Returns string representation of this object.
Returns
{string} String representation of this object
References CatSdk.BaseNetwork< T >.Name.
Member Data Documentation
AddressClass
Type CatSdk.BaseNetwork< T >.AddressClass
Referenced by CatSdk.BaseNetwork< T >.BaseNetwork().
AddressHasher
readonly KeccakDigest CatSdk.BaseNetwork< T >.AddressHasher
Referenced by CatSdk.BaseNetwork< T >.BaseNetwork(), and CatSdk.BaseNetwork< T >.PublicKeyToAddress().
CreateAddress
readonly Func<byte[], byte[], T> CatSdk.BaseNetwork< T >.CreateAddress
Referenced by CatSdk.BaseNetwork< T >.BaseNetwork(), and CatSdk.BaseNetwork< T >.PublicKeyToAddress().
DatetimeConverter
readonly NetworkTimestampDatetimeConverter CatSdk.BaseNetwork< T >.DatetimeConverter
Referenced by CatSdk.BaseNetwork< T >.BaseNetwork(), CatSdk.BaseNetwork< T >.FromDatetime< E >(), and CatSdk.BaseNetwork< T >.ToDatetime().
Identifier
readonly byte CatSdk.BaseNetwork< T >.Identifier
Referenced by CatSdk.BaseNetwork< T >.BaseNetwork(), and CatSdk.BaseNetwork< T >.PublicKeyToAddress().
Name
readonly string CatSdk.BaseNetwork< T >.Name
Referenced by CatSdk.BaseNetwork< T >.BaseNetwork(), and CatSdk.BaseNetwork< T >.ToString().
NetworkTimestampClass
readonly Type CatSdk.BaseNetwork< T >.NetworkTimestampClass
Referenced by CatSdk.BaseNetwork< T >.BaseNetwork(), and CatSdk.BaseNetwork< T >.FromDatetime< E >().
The documentation for this class was generated from the following file:
Network.cs